#!/usr/bin/env bash

# By Emmanuel Oluyege

# Bash script that transfers a file from our client to a server

# To check if 3 parameters are passed

if [ $# -lt 4 ]
then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
