#!/usr/bin/env bash

# By Emmanuel Oluyege

# Bash script that transfers a file from our client to a server

# To check if 3 parameters are passed

if [[ "$#" -lt "3" ]]
  then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit
  fi

scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
