#!/usr/bin/env bash
# Installation and configuration of  HAproxy on your lb-01 server.

# Install HAproxy on a server
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get update
apt-get install -y haproxy=2.4.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

# haproxy configuration with roundrobin algorithm
echo '
frontend noble-man.tech
        bind 0:80
        default_backend web_servers
backend web_servers
        balance roundrobin
        server 177494-web-01 174.129.55.27
        server 177494-web-01 18.234.107.4
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
