#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.4.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend noble-man.tech
        bind 0:80
        default_backend web_servers
backend web_servers
        balance roundrobin
        server 177494-web-01 174.129.55.27
        server 177494-web-02 18.234.107.4
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
