#!/usr/bin/env bash

# Configure ssh client to use public key authentication and other settings
Host *

# By Emmanuel Oluyege

    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
